import type { Dish } from './types.js';

const ts = () => new Date().toISOString();

/** Platos adicionales: pizzas, pasta, cazuelas, asiático, burgers… */
export function extraDishes(): Dish[] {
  return [
    {
      id: 'd-pizza-4formaggi',
      restaurant_id: 'r-forno-21',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'pizza-quattro-formaggi',
      name: 'Pizza quattro formaggi',
      description: 'Gorgonzola, parmesano, mozzarella y fontina al horno de leña.',
      long_description:
        'Masa napolitana de 48h, salsa de tomate ligera y mezcla de gorgonzola DOP, parmigiano reggiano, mozzarella fior di latte y fontina gratinada al horno de leña.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1590,
      vat_rate: 0.1,
      delivery_time_min: 32,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pizza', 'vegetariano'],
      allergens: ['gluten', 'lacteos'],
      ingredients: ['masa', 'mozzarella', 'gorgonzola', 'parmesano', 'fontina', 'tomate'],
      nutrition: { kcal: 810, protein_g: 34, carbs_g: 78, fat_g: 38 },
      portion: '350 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: true,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-pizza-pepperoni',
      restaurant_id: 'r-forno-21',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'pizza-pepperoni',
      name: 'Pizza pepperoni americana',
      description: 'Pepperoni ahumado, mozzarella y orégano.',
      long_description: 'Base crujiente estilo NY, salsa de tomate dulce, mozzarella y pepperoni ahumado en rodajas con orégano fresco.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1490,
      vat_rate: 0.1,
      delivery_time_min: 30,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pizza', 'popular'],
      allergens: ['gluten', 'lacteos'],
      ingredients: ['masa', 'tomate', 'mozzarella', 'pepperoni', 'orégano'],
      nutrition: { kcal: 860, protein_g: 36, carbs_g: 82, fat_g: 42 },
      portion: '360 g',
      is_available: true,
      is_featured: false,
      spicy_level: 1,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-pizza-vegana',
      restaurant_id: 'r-forno-21',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'pizza-vegana-verde',
      name: 'Pizza vegana verde',
      description: 'Base de coliflor, pesto, calabacín y cherry.',
      long_description:
        'Masa de coliflor horneada, pesto de albahaca y piñones, calabacín a la plancha, tomates cherry confitados y queso vegano de anacardos.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1390,
      vat_rate: 0.1,
      delivery_time_min: 28,
      rating: 4.6,
      images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pizza', 'vegano'],
      allergens: ['frutos_secos'],
      ingredients: ['base coliflor', 'pesto', 'calabacín', 'cherry', 'queso vegano'],
      nutrition: { kcal: 620, protein_g: 18, carbs_g: 58, fat_g: 32 },
      portion: '330 g',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-lasagna',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'lasana-bolognesa',
      name: 'Lasaña boloñesa gratinada',
      description: 'Capas de pasta fresca, ragú de ternera y bechamel.',
      long_description:
        'Pasta fresca artesanal, ragú de ternera cocinado 4 horas, bechamel de parmesano y gratinado al horno hasta dorar.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1290,
      vat_rate: 0.1,
      delivery_time_min: 35,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1574894709920-7b0e6b8b2b8a?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pasta', 'popular'],
      allergens: ['gluten', 'lacteos', 'huevos'],
      ingredients: ['pasta', 'ragú de ternera', 'bechamel', 'parmesano'],
      nutrition: { kcal: 720, protein_g: 38, carbs_g: 62, fat_g: 34 },
      portion: '400 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-carbonara',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'spaghetti-carbonara',
      name: 'Spaghetti carbonara romana',
      description: 'Guanciale crujiente, yema, pecorino y pimienta negra.',
      long_description: 'Spaghetti al dente con guanciale crujiente, crema de yema y pecorino romano DOP y pimienta negra recién molida.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1190,
      vat_rate: 0.1,
      delivery_time_min: 28,
      rating: 4.9,
      images: ['https://images.unsplash.com/photo-1612874742137-652c2a9d3653?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pasta', 'popular'],
      allergens: ['gluten', 'lacteos', 'huevos'],
      ingredients: ['spaghetti', 'guanciale', 'yema', 'pecorino', 'pimienta'],
      nutrition: { kcal: 680, protein_g: 28, carbs_g: 72, fat_g: 30 },
      portion: '380 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-pesto',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'tagliatelle-pesto',
      name: 'Tagliatelle al pesto genovese',
      description: 'Albahaca, piñones tostados, parmesano y aceite de oliva.',
      long_description: 'Tagliatelle frescas con pesto genovese de albahaca, piñones tostados, ajo, parmesano y aceite de oliva virgen extra.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1090,
      vat_rate: 0.1,
      delivery_time_min: 25,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1473093295047-4ddfd7ba2c7c?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pasta', 'vegetariano'],
      allergens: ['gluten', 'lacteos', 'frutos_secos'],
      ingredients: ['tagliatelle', 'albahaca', 'piñones', 'parmesano', 'aceite de oliva'],
      nutrition: { kcal: 640, protein_g: 22, carbs_g: 78, fat_g: 26 },
      portion: '370 g',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-ravioli',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'ravioli-ricotta-espinacas',
      name: 'Ravioli ricotta y espinacas',
      description: 'Mantequilla de salvia y parmesano rallado.',
      long_description: 'Ravioli rellenos de ricotta fresca y espinacas salteadas, servidos con mantequilla de salvia y parmesano.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1240,
      vat_rate: 0.1,
      delivery_time_min: 30,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1587740904311-2d7f4a2c4e0a?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pasta', 'vegetariano'],
      allergens: ['gluten', 'lacteos', 'huevos'],
      ingredients: ['ravioli', 'ricotta', 'espinacas', 'mantequilla', 'parmesano'],
      nutrition: { kcal: 590, protein_g: 24, carbs_g: 64, fat_g: 24 },
      portion: '360 g',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-risotto',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-pizzas-pasta',
      slug: 'risotto-setas',
      name: 'Risotto de setas silvestres',
      description: 'Arroz carnaroli, porcini, trufa y parmesano.',
      long_description: 'Risotto cremoso de arroz carnaroli con mix de setas silvestres, caldo de verduras, mantequilla, parmesano y aceite de trufa.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1340,
      vat_rate: 0.1,
      delivery_time_min: 32,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1476124369801-b43f9aef2f0b?auto=format&fit=crop&w=1200&q=80'],
      tags: ['pasta', 'vegetariano'],
      allergens: ['lacteos'],
      ingredients: ['arroz carnaroli', 'setas', 'parmesano', 'mantequilla', 'trufa'],
      nutrition: { kcal: 560, protein_g: 14, carbs_g: 82, fat_g: 18 },
      portion: '350 g',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-fabada',
      restaurant_id: 'r-la-cazuela',
      menu_section_id: 'sec-cazuelas',
      slug: 'fabada-asturiana',
      name: 'Fabada asturiana',
      description: 'Fabes, compango, chorizo y morcilla asturiana.',
      long_description:
        'Fabes de la granja cocidas a fuego lento con compango de lacón, chorizo asturiano y morcilla, en cazuela de barro.',
      category: 'main',
      cuisine: 'Española',
      price_cents: 1390,
      vat_rate: 0.1,
      delivery_time_min: 40,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80'],
      tags: ['cazuela', 'popular'],
      allergens: ['sulfitos'],
      ingredients: ['fabes', 'chorizo', 'morcilla', 'lacón', 'pimentón'],
      nutrition: { kcal: 780, protein_g: 32, carbs_g: 68, fat_g: 38 },
      portion: '450 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-callos',
      restaurant_id: 'r-la-cazuela',
      menu_section_id: 'sec-cazuelas',
      slug: 'callos-madrilenos',
      name: 'Callos a la madrileña',
      description: 'Trippa, chorizo, morcilla y guindilla en salsa picante.',
      long_description:
        'Callos de ternera estofados con chorizo, morcilla de Burgos, pimentón de la Vera y guindilla en cazuela de hierro.',
      category: 'main',
      cuisine: 'Española',
      price_cents: 1290,
      vat_rate: 0.1,
      delivery_time_min: 38,
      rating: 4.6,
      images: ['https://images.unsplash.com/photo-1604908176997-4313efdd2453?auto=format&fit=crop&w=1200&q=80'],
      tags: ['cazuela', 'picante'],
      allergens: ['sulfitos'],
      ingredients: ['callos', 'chorizo', 'morcilla', 'pimentón', 'guindilla'],
      nutrition: { kcal: 620, protein_g: 42, carbs_g: 12, fat_g: 44 },
      portion: '420 g',
      is_available: true,
      is_featured: false,
      spicy_level: 2,
      vegetarian: false,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-cocido',
      restaurant_id: 'r-la-cazuela',
      menu_section_id: 'sec-cazuelas',
      slug: 'cocido-madrileno',
      name: 'Cocido madrileño (ración)',
      description: 'Garbanzos, carnes, verduras y fideos en tres vuelcos.',
      long_description:
        'Ración generosa de cocido: garbanzos con su caldo, carnes de pollo y ternera, chorizo, morcilla y verduras de temporada.',
      category: 'main',
      cuisine: 'Española',
      price_cents: 1490,
      vat_rate: 0.1,
      delivery_time_min: 45,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1604908177522-402cfa3a0c0a?auto=format&fit=crop&w=1200&q=80'],
      tags: ['cazuela', 'popular'],
      allergens: ['gluten', 'sulfitos'],
      ingredients: ['garbanzos', 'pollo', 'ternera', 'chorizo', 'morcilla', 'verduras'],
      nutrition: { kcal: 920, protein_g: 48, carbs_g: 72, fat_g: 46 },
      portion: '500 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-gazpacho',
      restaurant_id: 'r-la-cazuela',
      menu_section_id: 'sec-entrantes',
      slug: 'gazpacho-andaluz',
      name: 'Gazpacho andaluz',
      description: 'Tomate, pepino, pimiento y AOVE, bien frío.',
      long_description: 'Gazpacho tradicional batido al momento con tomate pera, pepino, pimiento verde, ajo, vinagre de Jerez y aceite de oliva.',
      category: 'starter',
      cuisine: 'Española',
      price_cents: 590,
      vat_rate: 0.1,
      delivery_time_min: 15,
      rating: 4.6,
      images: ['https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80'],
      tags: ['cazuela', 'vegano'],
      allergens: [],
      ingredients: ['tomate', 'pepino', 'pimiento', 'ajo', 'aceite de oliva'],
      nutrition: { kcal: 120, protein_g: 3, carbs_g: 14, fat_g: 6 },
      portion: '400 ml',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-gyozas',
      restaurant_id: 'r-casa-nori',
      menu_section_id: 'sec-entrantes',
      slug: 'gyozas-cerdo',
      name: 'Gyozas de cerdo (6 uds)',
      description: 'Rellenas de cerdo y verduras, base crujiente.',
      long_description: 'Gyozas artesanas rellenas de cerdo y col china, selladas a la plancha y vaporizadas con salsa ponzu.',
      category: 'starter',
      cuisine: 'Asiática',
      price_cents: 690,
      vat_rate: 0.1,
      delivery_time_min: 18,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1496116218417-1a781b67df0e?auto=format&fit=crop&w=1200&q=80'],
      tags: ['entrante', 'popular'],
      allergens: ['gluten', 'soja', 'sesamo'],
      ingredients: ['masa gyoza', 'cerdo', 'col china', 'jengibre', 'salsa ponzu'],
      nutrition: { kcal: 320, protein_g: 16, carbs_g: 34, fat_g: 12 },
      portion: '6 piezas',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-padthai',
      restaurant_id: 'r-casa-nori',
      menu_section_id: 'sec-principales',
      slug: 'pad-thai-pollo',
      name: 'Pad thai de pollo',
      description: 'Fideos de arroz, tamarindo, cacahuete y lima.',
      long_description: 'Fideos de arroz salteados al wok con pollo, huevo, brotes, cacahuete tostado, tamarindo y lima fresca.',
      category: 'main',
      cuisine: 'Asiática',
      price_cents: 1190,
      vat_rate: 0.1,
      delivery_time_min: 28,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1559314809-0d31640f0a27?auto=format&fit=crop&w=1200&q=80'],
      tags: ['popular'],
      allergens: ['huevos', 'frutos_secos', 'pescado'],
      ingredients: ['fideos de arroz', 'pollo', 'huevo', 'cacahuete', 'tamarindo', 'lima'],
      nutrition: { kcal: 580, protein_g: 32, carbs_g: 68, fat_g: 18 },
      portion: '400 g',
      is_available: true,
      is_featured: false,
      spicy_level: 1,
      vegetarian: false,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-smash-doble',
      restaurant_id: 'r-prado-burger',
      menu_section_id: 'sec-principales',
      slug: 'smash-doble-bacon',
      name: 'Smash doble bacon',
      description: 'Doble carne, bacon ahumado, cheddar y salsa BBQ.',
      long_description: 'Doble smash de 90g cada una, bacon ahumado crujiente, doble cheddar y salsa BBQ ahumada en bollo de patata.',
      category: 'main',
      cuisine: 'Burgers',
      price_cents: 1490,
      vat_rate: 0.1,
      delivery_time_min: 28,
      rating: 4.9,
      images: ['https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=1200&q=80'],
      tags: ['burger', 'popular'],
      allergens: ['gluten', 'lacteos', 'huevos', 'mostaza'],
      ingredients: ['carne', 'bacon', 'cheddar', 'salsa BBQ', 'bollo'],
      nutrition: { kcal: 980, protein_g: 52, carbs_g: 48, fat_g: 62 },
      portion: '320 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-alitas',
      restaurant_id: 'r-prado-burger',
      menu_section_id: 'sec-sides',
      slug: 'alitas-bbq',
      name: 'Alitas BBQ picantes',
      description: '8 alitas glaseadas con salsa chipotle.',
      long_description: 'Alitas de pollo marinadas, fritas y glaseadas con salsa BBQ chipotle y semillas de sésamo.',
      category: 'side',
      cuisine: 'Burgers',
      price_cents: 790,
      vat_rate: 0.1,
      delivery_time_min: 22,
      rating: 4.6,
      images: ['https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=1200&q=80'],
      tags: ['side', 'picante'],
      allergens: ['sesamo'],
      ingredients: ['alitas de pollo', 'salsa BBQ', 'chipotle', 'sésamo'],
      nutrition: { kcal: 520, protein_g: 38, carbs_g: 18, fat_g: 32 },
      portion: '8 uds',
      is_available: true,
      is_featured: false,
      spicy_level: 2,
      vegetarian: false,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-croquetas',
      restaurant_id: 'r-la-cazuela',
      menu_section_id: 'sec-entrantes',
      slug: 'croquetas-jamon',
      name: 'Croquetas de jamón ibérico (6 uds)',
      description: 'Bechamel cremosa y rebozado crujiente.',
      long_description: 'Croquetas caseras de jamón ibérico de bellota con bechamel sedosa y rebozado panko dorado.',
      category: 'starter',
      cuisine: 'Española',
      price_cents: 690,
      vat_rate: 0.1,
      delivery_time_min: 20,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1604908177522-402cfa3a0c0a?auto=format&fit=crop&w=1200&q=80'],
      tags: ['entrante', 'popular'],
      allergens: ['gluten', 'lacteos', 'huevos'],
      ingredients: ['jamón ibérico', 'bechamel', 'harina', 'huevo', 'pan rallado'],
      nutrition: { kcal: 420, protein_g: 14, carbs_g: 38, fat_g: 24 },
      portion: '6 piezas',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-panna-cotta',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-postres',
      slug: 'panna-cotta-frutos',
      name: 'Panna cotta de frutos rojos',
      description: 'Crema italiana con coulis de frutos del bosque.',
      long_description: 'Panna cotta de vainilla con coulis de frutos rojos de temporada y crumble de almendra.',
      category: 'dessert',
      cuisine: 'Italiana',
      price_cents: 590,
      vat_rate: 0.1,
      delivery_time_min: 15,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80'],
      tags: ['postre'],
      allergens: ['lacteos', 'frutos_secos'],
      ingredients: ['nata', 'vainilla', 'frutos rojos', 'almendra'],
      nutrition: { kcal: 340, protein_g: 5, carbs_g: 42, fat_g: 16 },
      portion: '180 g',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-coca-cola',
      restaurant_id: 'r-prado-burger',
      menu_section_id: 'sec-bebidas',
      slug: 'coca-cola-lata',
      name: 'Coca-Cola',
      description: 'Lata 330 ml, bien fría.',
      long_description: 'Coca-Cola Original en lata de 330 ml. Servida bien fría.',
      category: 'drink',
      cuisine: 'Americana',
      price_cents: 220,
      vat_rate: 0.1,
      delivery_time_min: 5,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1554866585-2f025a5bdd65?auto=format&fit=crop&w=1200&q=80'],
      tags: ['bebida', 'refresco'],
      allergens: [],
      ingredients: ['agua carbonatada', 'azúcar', 'color caramelo', 'cafeína'],
      nutrition: { kcal: 139, protein_g: 0, carbs_g: 35, fat_g: 0 },
      portion: '330 ml',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-pepsi',
      restaurant_id: 'r-prado-burger',
      menu_section_id: 'sec-bebidas',
      slug: 'pepsi-lata',
      name: 'Pepsi',
      description: 'Lata 330 ml, bien fría.',
      long_description: 'Pepsi en lata de 330 ml. Servida bien fría.',
      category: 'drink',
      cuisine: 'Americana',
      price_cents: 220,
      vat_rate: 0.1,
      delivery_time_min: 5,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=1200&q=80'],
      tags: ['bebida', 'refresco'],
      allergens: [],
      ingredients: ['agua carbonatada', 'azúcar', 'color caramelo', 'cafeína'],
      nutrition: { kcal: 138, protein_g: 0, carbs_g: 35, fat_g: 0 },
      portion: '330 ml',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-fanta',
      restaurant_id: 'r-prado-burger',
      menu_section_id: 'sec-bebidas',
      slug: 'fanta-naranja-lata',
      name: 'Fanta Naranja',
      description: 'Lata 330 ml, sabor naranja.',
      long_description: 'Fanta Naranja en lata de 330 ml. Refresco sin cafeína.',
      category: 'drink',
      cuisine: 'Americana',
      price_cents: 220,
      vat_rate: 0.1,
      delivery_time_min: 5,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1624517452648-048a0c46dd66?auto=format&fit=crop&w=1200&q=80'],
      tags: ['bebida', 'refresco'],
      allergens: [],
      ingredients: ['agua carbonatada', 'azúcar', 'zumo de naranja'],
      nutrition: { kcal: 132, protein_g: 0, carbs_g: 33, fat_g: 0 },
      portion: '330 ml',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-aquarius',
      restaurant_id: 'r-verde-verde',
      menu_section_id: 'sec-bebidas',
      slug: 'aquarius-limon-lata',
      name: 'Aquarius Limón',
      description: 'Lata 330 ml, isotónica sabor limón.',
      long_description: 'Aquarius Limón en lata de 330 ml. Bebida isotónica sin gas añadido intenso.',
      category: 'drink',
      cuisine: 'Mediterránea',
      price_cents: 240,
      vat_rate: 0.1,
      delivery_time_min: 5,
      rating: 4.6,
      images: ['https://images.unsplash.com/photo-1546173159-315724a3160b?auto=format&fit=crop&w=1200&q=80'],
      tags: ['bebida', 'isotonica'],
      allergens: [],
      ingredients: ['agua', 'azúcar', 'limón', 'minerales'],
      nutrition: { kcal: 90, protein_g: 0, carbs_g: 22, fat_g: 0 },
      portion: '330 ml',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-monster',
      restaurant_id: 'r-prado-burger',
      menu_section_id: 'sec-bebidas',
      slug: 'monster-energy-lata',
      name: 'Monster Energy',
      description: 'Lata 500 ml, bebida energética.',
      long_description: 'Monster Energy en lata de 500 ml. Bebida energética con cafeína y taurina.',
      category: 'drink',
      cuisine: 'Americana',
      price_cents: 290,
      vat_rate: 0.1,
      delivery_time_min: 5,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1622543562537-54413184e6af?auto=format&fit=crop&w=1200&q=80'],
      tags: ['bebida', 'energetica'],
      allergens: [],
      ingredients: ['agua carbonatada', 'azúcar', 'cafeína', 'taurina', 'vitaminas'],
      nutrition: { kcal: 220, protein_g: 0, carbs_g: 54, fat_g: 0 },
      portion: '500 ml',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-menu-dia-paella',
      restaurant_id: 'r-la-cazuela',
      menu_section_id: 'sec-menu-dia',
      slug: 'menu-dia-paella-valenciana',
      name: 'Paella del día (2 pax)',
      description: 'Arroz bomba, pollo, judía verde y azafrán — ración para compartir.',
      long_description: 'Paella valenciana del día con arroz bomba, pollo de corral, judía ferradura y azafrán. Incluye alioli.',
      category: 'main',
      cuisine: 'Española',
      price_cents: 1890,
      vat_rate: 0.1,
      delivery_time_min: 35,
      rating: 4.9,
      images: ['https://images.unsplash.com/photo-1534080564583-591bebc13fec?auto=format&fit=crop&w=1200&q=80'],
      tags: ['menu-dia', 'paella'],
      allergens: ['crustaceos', 'moluscos'],
      ingredients: ['arroz bomba', 'pollo', 'judía verde', 'azafrán'],
      nutrition: { kcal: 720, protein_g: 38, carbs_g: 82, fat_g: 22 },
      portion: '2 personas',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: true,
      created_at: ts(),
    },
    {
      id: 'd-menu-dia-lasana',
      restaurant_id: 'r-pasta-luca',
      menu_section_id: 'sec-menu-dia',
      slug: 'menu-dia-lasana-bolo',
      name: 'Lasaña boloñesa del chef',
      description: 'Pasta fresca, ragú de ternera 8h y bechamel gratinada.',
      long_description: 'Capas de pasta fresca con ragú de ternera cocinado 8 horas, bechamel suave y parmesano gratinado.',
      category: 'main',
      cuisine: 'Italiana',
      price_cents: 1290,
      vat_rate: 0.1,
      delivery_time_min: 28,
      rating: 4.8,
      images: ['https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80'],
      tags: ['menu-dia', 'pasta'],
      allergens: ['gluten', 'lacteos', 'huevos'],
      ingredients: ['pasta', 'ternera', 'tomate', 'bechamel', 'parmesano'],
      nutrition: { kcal: 680, protein_g: 36, carbs_g: 58, fat_g: 32 },
      portion: '420 g',
      is_available: true,
      is_featured: true,
      spicy_level: 0,
      vegetarian: false,
      vegan: false,
      gluten_free: false,
      created_at: ts(),
    },
    {
      id: 'd-menu-dia-bowl',
      restaurant_id: 'r-verde-verde',
      menu_section_id: 'sec-menu-dia',
      slug: 'menu-dia-bowl-verde',
      name: 'Bowl verde del día',
      description: 'Quinoa, aguacate, edamame y vinagreta de limón.',
      long_description: 'Bowl equilibrado con quinoa, aguacate, edamame, zanahoria encurtida y vinagreta de limón y jengibre.',
      category: 'main',
      cuisine: 'Mediterránea',
      price_cents: 1090,
      vat_rate: 0.1,
      delivery_time_min: 22,
      rating: 4.7,
      images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80'],
      tags: ['menu-dia', 'saludable'],
      allergens: ['soja', 'sesamo'],
      ingredients: ['quinoa', 'aguacate', 'edamame', 'limón'],
      nutrition: { kcal: 480, protein_g: 18, carbs_g: 52, fat_g: 22 },
      portion: '380 g',
      is_available: true,
      is_featured: false,
      spicy_level: 0,
      vegetarian: true,
      vegan: true,
      gluten_free: true,
      created_at: ts(),
    },
  ];
}
